import type { NextPage } from 'next'
import Head from 'next/head'
import { HomeTemplate } from '../templates/Home'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chuck Facts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate/>
    </div>
  )
}

export default Home
