import type { NextPage } from 'next'
import Head from 'next/head'
import { Background } from '../components/atoms/Background'
import { Header } from '../components/molecules/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chuck Facts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background>
        <Header/>
      </Background>
    </div>
  )
}

export default Home
